import { type GetServerSideProps, type NextPage } from "next";
import { getToken } from "next-auth/jwt";
import Head from "next/head";
import { ParsedUrlQuery } from "querystring";

import PlaylistDetails from "~/components/playlist/PlaylistDetails";

interface Params extends ParsedUrlQuery {
  id: string;
}

import { getUserPlaylist } from "~/lib/spotify";

const Playlist: NextPage<{
  playlist: SpotifyApi.PlaylistObjectFull;
}> = ({ playlist }) => {
  return (
    <>
      <Head>
        <title>Playlists | Webify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="pt-20">
        <h1 className="mt-12 text-center text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
          <span className="text-white">{playlist.name}</span>
        </h1>

        <div className="container mx-auto mt-16 min-h-screen gap-12 px-4  ">
          <PlaylistDetails playlist={playlist} />
        </div>
      </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req } = ctx;
  const { id } = ctx.params as Params;

  const token = await getToken({ req });

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const playlist: SpotifyApi.PlaylistObjectFull = await getUserPlaylist(
    id,
    token?.access_token!
  );
  return {
    props: { playlist },
  };
};

export default Playlist;
