import { type GetServerSideProps, type NextPage } from "next";
import { getToken } from "next-auth/jwt";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { ParsedUrlQuery } from "querystring";
import { useState } from "react";

import PlaylistDetails from "~/components/playlist/PlaylistDetails";

interface Params extends ParsedUrlQuery {
  id: string;
}

import { getUserPlaylist, getUserPlaylistTracks } from "~/lib/spotify";

const Playlist: NextPage<{
  playlist: SpotifyApi.PlaylistObjectFull;
  tracks: SpotifyApi.PlaylistTrackObject[];
  totalPages: number;
}> = ({ playlist, totalPages, tracks }) => {
  const [currentPage, setCurrentPage] = useState(1);
  const [currentTracks, setCurrentTracks] = useState(tracks);

  const token = useSession();

  const setTracksPage = async (page: number) => {
    setCurrentPage(page);

    const newTracks = await getUserPlaylistTracks(
      playlist.id,
      token.data?.user.access_token!,
      10,
      page
    );

    setCurrentTracks(newTracks.tracks);
  };

  return (
    <>
      <Head>
        <title>Playlist | Webify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="pt-10">
        <h1 className="mt-12 text-center text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
          <span className="text-white">{playlist.name}</span>
        </h1>

        <div className="container mx-auto mt-16 gap-12 px-4  ">
          <PlaylistDetails
            playlist={playlist}
            totalPages={totalPages}
            page={currentPage}
            setTracksPage={setTracksPage}
            tracks={currentTracks}
          />
        </div>
      </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req } = ctx;
  const { id } = ctx.params as Params;

  const token = await getToken({ req });

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const playlist: SpotifyApi.PlaylistObjectFull = await getUserPlaylist(
    id,
    token?.access_token!
  );

  const { tracks, totalPages } = await getUserPlaylistTracks(
    id,
    token?.access_token!,
    10,
    1
  );

  return {
    props: { playlist, tracks, totalPages },
  };
};

export default Playlist;
