import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Home | Webify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-r from-orange-400 to-rose-400">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-white">Webify</span>
          </h1>

          <div className="text-white">
            {session ? (
              <div className="flex justify-center">
                <Link className="btn" href="/playlists">
                  Playlists
                </Link>
                <button className="btn" onClick={() => signOut()}>
                  Logout
                </button>
              </div>
            ) : (
              <button
                className="btn"
                type="button"
                onClick={() => signIn("spotify")}
              >
                Login
              </button>
            )}
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
