import { motion } from "framer-motion";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: session } = useSession();

  const title = {
    hidden: { opacity: 0, scale: 0.8 },
    show: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.5,
      },
    },
  };

  return (
    <>
      <Head>
        <title>Home | Webify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <motion.h1
            initial="hidden"
            animate="show"
            variants={title}
            className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]"
          >
            <span className="text-white">Webify</span>
          </motion.h1>

          <div className="text-white">
            {session?.user ? (
              <div className="flex justify-center">
                <button className="btn" onClick={() => signOut()}>
                  Logout
                </button>
              </div>
            ) : (
              <button
                className="btn"
                type="button"
                onClick={() => signIn("spotify")}
              >
                Login
              </button>
            )}
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
