import { GetServerSideProps, type NextPage } from "next";
import { getToken } from "next-auth/jwt";
import Head from "next/head";
import Playlist from "~/components/playlists";
import { getUsersPlaylists } from "~/lib/spotify";

const Playlists: NextPage<{
  userPlaylists: SpotifyApi.ListOfUsersPlaylistsResponse;
}> = ({ userPlaylists }) => {
  return (
    <>
      <Head>
        <title>Playlists | Webify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-r from-orange-400 to-rose-400 pt-20">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            <span className="text-white">Playlists</span>
          </h1>

          <div className="text-white">
            {userPlaylists ? <Playlist list={userPlaylists} /> : null}
          </div>
        </div>
      </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const token = await getToken({ req });

  const userPlaylists = await getUsersPlaylists(token?.access_token!);

  return {
    props: { userPlaylists },
  };
};

export default Playlists;
