import { type GetServerSideProps, type NextPage } from "next";
import { getToken } from "next-auth/jwt";
import Head from "next/head";
import PlaylistContainer from "~/components/playlist/playlistContainer";
import { getUsersPlaylists } from "~/lib/spotify";

const Playlists: NextPage<{
  userPlaylists: SpotifyApi.ListOfUsersPlaylistsResponse;
}> = ({ userPlaylists }) => {
  return (
    <>
      <Head>
        <title>Playlists | Webify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-gradient-to-r from-orange-400 to-rose-400 pt-20">
        <h1 className="mt-12 text-center text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
          <span className="text-white">Playlists</span>
        </h1>

        <div className="container mx-auto mt-16 min-h-screen gap-12 px-4  ">
          {userPlaylists ? <PlaylistContainer list={userPlaylists} /> : null}
        </div>
      </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const token = await getToken({ req });

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const userPlaylists: SpotifyApi.ListOfUsersPlaylistsResponse =
    await getUsersPlaylists(token?.access_token!);

  return {
    props: { userPlaylists },
  };
};

export default Playlists;
